# -*- coding: utf-8 -*-
"""Evidence ledger for the Reforge external research (all sources checked 2026-10-03)."""

ACCESS = "2026-10-03 访问"


def ev(id, title, nature, date, locator, url, support, limitation):
    return dict(id=id, title=title, nature=nature, date=date, locator=locator,
                url=url, support=support, limitation=limitation)


EVIDENCE = [
    # ---------- Reforge：官网与官方博客 ----------
    ev("e-home", "Reforge 官网首页", "公司官网（自述营销口径）", ACCESS,
       "首页：直播课主题、40+ 按需课程、600+ 指南、1,400+ Artifacts、『Join 1K+ other high-performing product teams』",
       "https://www.reforge.com/",
       "支持 2026-10 仍以学习产品为主页内容，并以团队为主要销售对象。",
       "『1K+ 产品团队』未说明是否为当前付费团队、统计时间与去重口径。"),
    ev("e-pricing", "Reforge 定价页", "公司官网（标价）", ACCESS,
       "Individual $1,995/年 1 席；Starter $9,995/年 10 席；Scale $23,995/年 30 席；Enterprise 50+ 席定制",
       "https://www.reforge.com/pricing",
       "支持当前标价与按席位的团队售卖结构。",
       "标价不等于成交价；折扣、续费价与各档客户数未公开；页面未提及 AI 工具。"),
    ev("e-courses", "Reforge 课程页", "公司官网（课程目录）", ACCESS,
       "Live 课程 9 门：AI Transformation、AI Evals、AI Prototyping、Product Foundations for the AI Era、AI Productivity、AI Strategy、AI Product Leadership、AI Growth、Growth Foundations",
       "https://www.reforge.com/courses",
       "支持 2026 年学习业务仍在运营，且直播课集中到 AI 主题。",
       "页面未列开课日期与报名人数；讲师所属公司未在抓取内容中显示。"),
    ev("e-joining-miro", "Reforge is joining Miro（Brian Balfour）", "公司官方公告", "2026-03-24",
       "Reforge 博客：Learning 保持独立品牌；Insights、Research、Build 并入 Miro Product Acceleration；春季 cohort 不变、价格不变；『over 100,000 alumni』；约 10 年前与 Andrew Chen 做首个 Growth Series",
       "https://www.reforge.com/blog/reforge-is-joining-miro",
       "支持收购事实、产品去向、学习业务安排与累计学员口径。",
       "未披露收购对价、收入、在职人数；『alumni』为累计口径。"),
    ev("e-miro-blog", "Miro + Reforge（Andrey Khusid）", "收购方官方公告", "2026-03-24",
       "Miro 博客：收购 Reforge 的人员、学习平台与产品（待交割条件）；Balfour 任 Chief Growth Officer，Willerer 任 Chief Strategy Officer；『Reforge’s 100,000 learners』",
       "https://miro.com/blog/reforge-joins-miro-team/",
       "支持收购范围、高管安排与收购方给出的战略理由。",
       "收购方叙述，未给出条款与 Reforge 经营数据。"),
    ev("e-itbrief", "Miro acquires Reforge to boost AI product strategy", "行业媒体报道", "2026-03-26",
       "IT Brief：条款未披露；客户含 Workday、Xero、SAP、Mastercard、Netflix；Miro 1 亿+用户、25 万客户、1,600+ 员工",
       "https://itbrief.com.au/story/miro-acquires-reforge-to-boost-ai-product-strategy",
       "支持交易条款未披露与客户名单（公司提供）。",
       "客户名单来自公司口径，不代表客户规模或续约。"),
    ev("e-classcentral", "Miro Acquires Reforge: This Is Not an Edtech Deal（转载）", "行业分析的转载副本（原文 Class Central）", "2026-04-02（转载日期）",
       "Virtual Job Guru 转载：『shipped five AI products in nine months』（Build、Insights、Research、Launch、Artifacts）；$30M 收入称为 2023 年 Balfour 说法；裁员 2022-10、2023-04、2024-10（只留约 25% 团队）",
       "https://blog.virtualjobguru.com/miro-acquires-reforge-this-is-not-an-edtech-deal/",
       "提供 2024-10 第三轮裁员与『约 25% 留任』的线索，以及收购偏重工具与人才的解读。",
       "Class Central 原站对本次访问返回 403，未能核对原文；第三轮裁员没有找到 Reforge 原始公告；$30M 的时期与 Chargebee 摘要不一致。"),
    ev("e-build-redirect", "build.reforge.com 跳转记录", "研究者访问记录", ACCESS,
       "reforge.com/build → build.reforge.com（302）→ miro.com/try-prototyping/（303）；reforge.com/insights 显示 404",
       "https://build.reforge.com/",
       "支持 Build 已转入 Miro 的产品入口、Insights 独立页面已下线。",
       "跳转只说明入口变化，不说明产品是否继续收费或用户迁移情况。"),
    ev("e-bending-spoons", "Bending Spoons agrees to buy Miro for $1.355bn", "行业媒体报道", "2026-09-10",
       "The Next Web：企业价值 $1.355B、全现金、预计 2026 Q4 交割；Miro 约 $600M ARR；Bending Spoons 称会重组团队、改善变现",
       "https://thenextweb.com/news/bending-spoons-miro-acquisition-1-355bn",
       "支持 Reforge 的新母公司本身正被收购、学习业务归属存在不确定性。",
       "报道未提及 Reforge；交割与交割后安排尚未发生。"),
    ev("e-a16z-reforge", "Investing in Reforge（Andrew Chen）", "领投方公开说明", "2021-02-23",
       "a16z：2015 年启动并自举；年度会员＋多周 cohort；『thousands』学员靠口碑；Chen 帮助发起第一个获客／留存项目并加入董事会",
       "https://a16z.com/announcement/investing-in-reforge/",
       "支持早期模式、口碑获客说法以及 Chen 的双重角色（共建者与投资人）。",
       "投资人叙述，非独立数据；无收入或会员数字。"),
    ev("e-raise-21m", "We’ve Raised $21M To Grow Reforge", "公司官方公告", "2021-02-24",
       "Reforge 博客：2015 年以 SVBR Growth Series 起步；10 个项目覆盖增长、产品、营销、工程；每个项目与前沿操盘手共建 50–100 小时；资金用于新项目、社区、EIR／OIR",
       "https://www.reforge.com/blog/weve-raised-21m-to-grow-reforge",
       "支持 2021 年项目数、内容生产方式与融资用途。",
       "公司自述；『数千名』学员未给精确数。"),
    ev("e-balfour-21m", "Why We Raised $21M After Bootstrapping To An 8-Figure Revenue, Profitable Company", "创始人自述", "2021-02-24",
       "brianbalfour.com：自举 5 年、8 位数收入且盈利；想从每年少量新题扩到 30+ 题目，现金流不足以支撑",
       "https://brianbalfour.com/quick-takes/why-we-raised-21m-after-bootstrapping-to-an-8-figure-revenue-profitable-company",
       "支持融资前收入量级、盈利状态与融资理由。",
       "创始人自述、未审计；『8 位数』只给量级。"),
    ev("e-series-b", "Reforge Raises $60M to Power The Expertise Economy", "公司官方公告", "2022-03-03",
       "Reforge 博客：B 轮 $60M，Insight Partners 领投，a16z、TCV 等与 170+ 高管参投；4–6 周 cohort；产品 6、增长 5、工程 3、营销 2 个项目",
       "https://www.reforge.com/blog/reforge-raises-series-b",
       "支持 B 轮金额、投资方与 2022-03 项目结构。",
       "未给收入、会员数或资金具体分配。"),
    ev("e-amplitude-2016", "Brian Balfour On ‘Coming Home To Growth’", "第三方访谈（Amplitude 博客）", "2016-06-30",
       "文中称 Balfour 与时任 Uber 增长负责人 Andrew Chen 共同主持 8 周 growth series；Balfour 曾联合创办 Viximo、任 HubSpot 增长 VP",
       "https://amplitude.com/blog/brian-balfour-coming-home-growth",
       "支持 2016 年时项目已在运行及创始人背景。",
       "未给价格、人数、招生方式。"),
    ev("e-muas", "How to grow a growth education business with Brian Balfour", "播客文字稿（重播）", "2022-11-21（重播日期；原始录制时间不明）",
       "Mobile User Acquisition Show 文字稿：『We had about 1000 applications』；『NPS scores from the MVP went from 20 to 72』；内容回路『my blog, and Andrew’s blog』驱动申请；按适配录取而非收入最大化；录制时有 4 门课",
       "https://mobileuseracquisitionshow.com/episode/how-to-grow-a-growth-education-business-with-brian-balfour-ceo-at-reforge/",
       "支持首期申请量、MVP 迭代、渠道与筛选取舍。",
       "创始人口述；文字稿写『fall of 2018 was when we did the full SVBR』，与 2015–2016 年起步的多份资料冲突，疑为转写或口误，年份不采用。"),
    ev("e-tweet-2019", "Balfour：Spring 2019 cohort 开放申请", "创始人社交帖（仅见搜索摘要）", "2019-02-28（按推文 ID 推算）",
       "推文摘要：与 Andrew Chen、Casey Winters、Shaun Clowes、Kevin Kwok 一起开放 Spring 2019 申请",
       "https://twitter.com/bbalfour/status/1101207921986138112",
       "支持 2019 年已采用多位合作讲师的季节性 cohort。",
       "X 页面未能直接抓取，只依据搜索结果摘要。"),
    ev("e-eir-2019", "Launching the Reforge EIR program", "创始人社交帖（经 Andrew Chen 转发）", "2019-11-14（按帖子 ID 推算）",
       "LinkedIn：EIR 为 6 或 12 个月、面向职业转换期的产品负责人；2020-01 选 2 人、2020 夏再选 2 人",
       "https://www.linkedin.com/posts/andrewchen_launching-the-reforge-eir-expert-in-residence-activity-6600823900295303168-e4k_",
       "支持 EIR 计划的起点与规模。",
       "未含报酬细节（招聘页另称有部分薪酬）。"),
    ev("e-eir-2022", "Announcing Reforge’s Summer 2022 Executives in Residence", "公司官方公告", "2022-06-14",
       "Reforge 博客：9 位 EIR（2 新 7 续）；新 EIR 含 Tom Willerer（前 Opendoor、Coursera CPO，Netflix）",
       "https://www.reforge.com/blog/new-reforge-eirs",
       "支持专家供给机制与 Willerer 的加入路径。",
       "未披露报酬与工作量。"),
    ev("e-fall-2022", "Balfour：Fall 2022 cohort", "创始人社交帖", "2022-08-23（按帖子 ID 推算）",
       "LinkedIn：秋季约 20 个项目、3 门新课、50+ 讲师（Notion、Spotify、Slack、HubSpot 等）",
       "https://www.linkedin.com/posts/bbalfour_hard-to-believe-when-andrew-chen-and-i-created-activity-6967872499350986753-cxtl",
       "支持扩题峰值规模。",
       "『约 20』为帖子口径；未给报名与付费数。"),
    ev("e-layoff-2022", "Balfour：2022-11 裁员帖", "创始人社交帖", "2022-11-11（按帖子 ID 推算）",
       "LinkedIn：『necessary step given the macroeconomic outlook』；『I am the sole owner for this decision』；涉及工程、产品、营销、招聘、运营、内容",
       "https://www.linkedin.com/posts/bbalfour_today-i-made-the-difficult-decision-to-activity-6996635113606316033-aQuf",
       "支持第一轮裁员时间与自述原因（宏观）。",
       "未给人数；自述原因不等于唯一原因。"),
    ev("e-layoff-2023", "Balfour：2023-04 裁员帖", "创始人社交帖", "2023-04-12（按帖子 ID 推算）",
       "LinkedIn：『broader strategic shift』；不影响当期 cohort；变化稍后公布",
       "https://www.linkedin.com/posts/bbalfour_today-i-made-the-difficult-decision-to-part-activity-7051721504803229697-4wf_",
       "支持第二轮裁员与战略调整的时间。",
       "未给人数（第三方站点称 45 人，未核实）。"),
    ev("e-teams-2023", "Announcing Our New Pricing and Teams Product", "公司官方公告", "2023-05-30",
       "Reforge 博客：『Over half of our current members are on team accounts』；个人 $1,995 由含 2 个 cohort 名额改为 1 个；新增团队合集、评论、参与度报表",
       "https://www.reforge.com/blog/2023-teams-announcement",
       "支持付款单位向团队转移及个人会员内容缩减。",
       "『过半』口径（人数还是收入）未说明；无续费数据。"),
    ev("e-changes-2023", "An Inside Look at Upcoming Changes in Reforge", "公司官方公告", "2023-12-07",
       "Reforge 博客：Artifacts 并入会员；Guides；AI 搜索；直播课由每年两次改为每月；经典项目改为按需",
       "https://www.reforge.com/blog/an-inside-look-at-upcoming-changes-in-reforge",
       "支持从季节性 cohort 转向常年内容与工作素材。",
       "没有说明调整前后的使用或续费变化。"),
    ev("e-extension-2024", "How We Built The Reforge Extension（Dan Wolchonok）", "公司官方博客", "2024-06-20",
       "Reforge 博客：插件在 Google Docs、Notion 等内起草与点评文档；2–3 人团队；『it’s always been a challenge to regularly apply the extensive content to everyday work』",
       "https://www.reforge.com/blog/howwebuiltit",
       "支持『学→做』缺口是转向工具的公开理由之一。",
       "无用户数与付费数据。"),
    ev("e-monterey", "Monterey AI is joining Reforge", "被收购方官方社交帖（仅见搜索摘要）", "2025-01-15（按推文 ID 推算）",
       "X：Monterey AI 宣布并入 Reforge；第三方整理称其更名为 Reforge Insight Analytics，处理客户反馈汇总与分析",
       "https://x.com/montereyai/status/1879584011758325806",
       "支持 2025-01 通过收购获得 Insights 产品与创始团队。",
       "X 页面未直接抓取；收购金额未披露。"),
    ev("e-spring-2025", "Spring 2025: Our Most Important Cohort Yet（Brian Balfour）", "公司官方博客", "2025-02-07",
       "Reforge 博客：『This year marks 10 years since we launched our first Reforge course』；直播＋按需共 40 门课；新增 AI Foundations、AI Productivity、AI Strategy",
       "https://www.reforge.com/blog/spring-2025-our-most-important-cohort-yet",
       "支持首门课在 2015 年、学习业务在 2025 年转向 AI 主题。",
       "无报名或会员数字。"),
    ev("e-build-2025", "Sachin Rekhi 谈 Reforge Build 发布", "Reforge 讲师的社交帖（仅见搜索摘要）", "2025-11-12（按推文 ID 推算）",
       "X 摘要：『today’s launch of @Reforge Build』，面向产品团队的 AI 原型工具",
       "https://x.com/sachinrekhi/status/1988637999949881413",
       "支持 Build 的发布时间。",
       "发帖人是 Reforge 讲师，非中立来源；页面未直接抓取。"),
    ev("e-supra", "#84: How Reforge launched 5 AI products in 9 months with just 25 people", "播客节目说明（Supra Insider）", "2025-11-17",
       "节目说明：『just 25 people』；时间轴含『why Reforge moved into tools』『How Reforge thinks about startup acquisitions』",
       "https://suprainsider.substack.com/p/84-how-reforge-launched-5-ai-products",
       "支持转型期团队规模与『学→做』的转向理由。",
       "未取得完整文字稿；产品名单与日期不完整。"),
    ev("e-promptled", "How Reforge Transformed From Education Company To Multi-Product Platform", "访谈整理（Prompt-led Product）", "2025 年（具体日期未取得）",
       "作者整理 Balfour 访谈：团队 25 人；约 25% 员工能转到产品公司；公司内含 7 位前创始人；2024 年末两次收购以补创业型人才",
       "https://promptledproduct.substack.com/p/how-reforge-transformed-from-education",
       "支持转型的组织方式与人才来源。",
       "第三方整理，部分为作者表述；未见原始音频时间戳。"),
    ev("e-chargebee", "Reforge’s Brian Balfour on second acts…（Chargebee 播客摘要）", "播客摘要（Chargebee 撰写）", "2025-12-19（更新日期）",
       "『Bootstrapped to $10M in four years』；『After venture funding, it grew to $30M in 18 months』；『Our biggest churn response has always been: I love Reforge, I just don’t need it right now.』；『~40 people and 4–5 products』",
       "https://www.chargebee.com/blog/reforges-brian-balfour-on-second-acts-a-foundational-law-of-retention-ai-native-product-teams-and-more/",
       "支持收入轨迹、流失原因（需求阶段性）与 2025 年末团队规模。",
       "Chargebee 撰写的摘要，不是逐字稿；收入口径（ARR 或确认收入）未说明、未审计。"),
    ev("e-willerer", "Tom Willerer · Reforge COO（The Org）", "整理型人物资料", ACCESS,
       "搜索摘要：2022-05 至 2023-08 任 Reforge EIR，2023-07 起任 COO；曾任 Coursera CPO、Opendoor CPO、Netflix 产品 VP",
       "https://theorg.com/org/reforge/org-chart/tom-willerer",
       "支持 Willerer 由 EIR 转为 COO 的时间线索。",
       "整理站资料，源自公开履历，未与公司公告逐项核对。"),
    ev("e-expense", "Can I expense my Reforge Membership to my company?", "公司帮助中心", "2026-09-09（更新日期）",
       "Reforge 帮助中心：『many companies … will reimburse their employees for membership』，建议联系经理或 HR",
       "https://reforge.helpscoutdocs.com/article/82-can-i-expense-my-reforge-membership-to-my-company",
       "支持雇主 L&D 预算是设计中的付款来源。",
       "未给报销比例；网传『约一半会员报销』未找到原始出处，未采用。"),
    ev("e-lenny-balfour", "Brian Balfour: 10 lessons on career, growth, and life", "播客节目说明（Lenny’s Podcast）", "2023-10-05（按推文 ID 推算）",
       "节目说明：Balfour 为 Reforge 创始人兼 CEO，曾任 HubSpot 增长 VP，此前联合创办三家创业公司",
       "https://www.lennysnewsletter.com/p/brian-balfour-10-lessons-on-career",
       "支持创始人背景。",
       "节目说明不含 Reforge 经营数据。"),
    ev("e-holoniq", "2022 EdTech VC funding totals $10.6B, down 49% from $20.8B in 2021", "研究机构统计（HolonIQ）", "2023-01-03",
       "HolonIQ：2022 全球 edtech 风险投资 $10.6B，较 2021 年 $20.8B 降 49%；基于 1,400+ 轮融资",
       "https://www.holoniq.com/notes/2022-edtech-vc-funding-totals-10-6b-down-from-20-8b-in-2021",
       "支持 2022 年教育赛道资本环境急转直下。",
       "衡量的是投资而非学员需求或企业培训预算；定义排除部分 HR 技术。"),
    ev("e-maven-claim", "聚合页称『Reforge 2023 年收购 Maven 课程平台』", "无来源的营销型聚合页（经搜索摘要看到）", ACCESS,
       "搜索摘要将该说法归于 businessmodelcanvastemplate.com 的 Reforge 增长策略页；该域名在本次访问时无法解析",
       "https://businessmodelcanvastemplate.com/blogs/growth-strategy/reforge-growth-strategy",
       "仅记录一条被排除的说法及排除过程。",
       "没有引用任何原始来源；与 Maven 官方资料矛盾，不作为事实使用。"),
    # ---------- Maven ----------
    ev("e-maven-a16z", "Investing in Maven（Andrew Chen）", "领投方公开说明", "2021-05-20",
       "a16z：2021-01 上线以来课程销售超 $1M；4 门课前三个月各超 $100K；创始人分别来自 Udemy、altMBA、Socratic；Chen 入董事会",
       "https://a16z.com/announcement/investing-in-maven/",
       "支持 Maven 起点资产与首批交易。",
       "投资人叙述；未给抽成比例。"),
    ev("e-maven-tc", "Maven’s a16z-backed live learning platform pivots from creators to experts", "媒体报道（TechCrunch，经 Yahoo 转载）", "2022-09-13",
       "18 个月课程销售 $9M；300+ cohort；从网红创作者转向专家；累计融资 $25M；『Just because somebody is a creator doesn’t mean they will run a successful course』",
       "https://finance.yahoo.com/news/mavens-a16z-backed-live-learning-160008761.html",
       "支持 Maven 早期路径与供给侧转向。",
       "销售额为平台 GMV，不是 Maven 收入。"),
    ev("e-maven-li", "Gagan Biyani：Maven 讲师累计销售过 $20M", "创始人社交帖", "2023-11-14（按帖子 ID 推算）",
       "LinkedIn：累计 $20M 课程销售；250,000+ 用户；40+ 讲师过 $100K；70% 完课率；25% 销售来自 Maven 市场；15 名全职远程员工",
       "https://www.linkedin.com/posts/gaganbiyani_so-proud-to-share-that-maven-instructors-activity-7130206160359428097-I4cE",
       "支持 Maven 在 2022–23 行业下行期仍增长、团队极轻。",
       "创始人自述 GMV；完课率口径未说明。"),
    ev("e-maven-fee", "Maven Help Center：Getting paid", "平台帮助中心", "2025-03-13（更新日期）",
       "『you keep 90% of your course earnings minus Stripe fees』；『Maven’s fee is 10%』",
       "https://help.maven.com/en/articles/5593804-getting-paid",
       "支持 Maven 对讲师的分成条件。",
       "企业代售等特殊项目另有分成。"),
    ev("e-maven-guide", "Maven Expert Policy Guidebook", "竞争对手帮助中心", ACCESS,
       "『significantly more instructor-friendly than other course platforms (for example, Reforge keeps 50%, Uplimit keeps 70%)』",
       "https://help.maven.com/en/articles/12240853-maven-instructor-policy-guidebook",
       "提供讲师供给侧竞争的线索。",
       "竞争对手单方说法，未经 Reforge 确认，不作为 Reforge 分成事实。"),
    ev("e-maven-secondary", "How Gagan Biyani built Maven to $100K ARR in 6 months", "二手整理（引用 Biyani 帖子与 First Round 文章）", ACCESS,
       "称 2020-10 创立；上线三个月 GMV 年化 $4M；讲师收入留存 73%，到 2024-06 为 120–140%；转向专家后丢掉约 95% 早期收入",
       "https://startupfounderstories.com/stories/gagan-biyani-maven-cohort-course-pmf",
       "提供 Maven 供给侧留存改善的线索。",
       "二手整理，原帖（X）未能抓取；数字只作线索。"),
    # ---------- Lenny's Newsletter ----------
    ev("e-lenny-2020", "How Lenny Rachitsky earned $65,000 in his first year of writing", "平台专访（Substack 官方博客）", "2020-08-01",
       "免费写作约 10 个月后推出付费，$15/月；首两天 200 付费；后为 15,000 免费、500 付费、年约 $65K；增长来自推文、客座文章、每周问答",
       "https://on.substack.com/p/how-lenny-rachitsky-earned-65000",
       "支持 Lenny 首次交易与早期增长动作。",
       "Lenny 自述；未扣除费用与税。"),
    ev("e-lenny-fr", "Reluctantly Influential: Inside Lenny Rachitsky’s Demandingly Chill Life", "深度专访（First Round Review）", "2026-04-15",
       "约 120 万订阅；不雇全职员工、约 10 名合同工；2022 年开播客；社区约 4 万人；拒绝 99.9% 合作请求；不做付费广告；拒绝透露收入",
       "https://review.firstround.com/reluctantly-influential-inside-lenny-rachitskys-demandingly-chill-life/",
       "支持 Lenny 的当前规模、组织方式与主动取舍。",
       "专访自述；付费人数与收入未公开；文中部分时间表述与 2020 年专访有出入。"),
    ev("e-lenny-about", "Lenny’s Newsletter About", "官网自述", ACCESS,
       "『Join 1,000,000+ subscribers』；付费含私有 Slack（30k+）、15+ 产品一年免费；提供向经理申请 L&D 报销的模板邮件",
       "https://www.lennysnewsletter.com/about",
       "支持雇主报销也是 Lenny 的付款来源之一。",
       "订阅数含免费订阅。"),
    ev("e-lenny-pass", "Lenny’s Product Pass", "官网标价", ACCESS,
       "Annual $200/年（22 个工具）；Insider $400/年（34 个工具）；称总价值 $39,000+；多数优惠限新客户",
       "https://www.lennysproductpass.com/",
       "支持当前价格与捆绑结构。",
       "工具『价值』为标价合计，不是用户实际使用价值。"),
    ev("e-lenny-bundle", "Announcing the greatest product bundle ever", "官方公告", "2025-02-04",
       "年度订阅送 Granola、Notion、Superhuman、Linear、Perplexity 一年",
       "https://www.lennysnewsletter.com/p/announcing-the-greatest-product-bundle",
       "支持捆绑开始时间。",
       "正文多为付费内容，理由与效果未公开。"),
    ev("e-lenny-cnbc", "Lenny Rachitsky brings in over $500,000 from his podcast", "媒体报道（CNBC，仅见标题）", "2024-01-11",
       "标题：播客年收入超 $500,000",
       "https://www.cnbc.com/2024/01/11/lenny-rachitsky-podcast-brings-in-more-than-500k-a-year-heres-how.html",
       "支持播客已成为独立收入来源。",
       "正文访问返回 403，仅依据标题。"),
    # ---------- Section ----------
    ev("e-section-tc", "Scott Galloway’s edtech startup, Section4, lays off a quarter of staff", "媒体报道（TechCrunch）", "2022-05-12",
       "裁员 32 人（约 25%）；CEO 称财务管理失误、尚无 PMF、招人过多、课程制作成本高；2021-03 A 轮 $30M；最初 2–3 周课 $995；2022-03 改为会员；转向企业",
       "https://techcrunch.com/2022/05/12/professor-scott-galloways-edtech-startup-section-4-lay-offs/",
       "支持 Section 的起点、首个产品与 2022 年收缩原因。",
       "CEO 自述原因；无收入数据。"),
    ev("e-section-pq", "Section4 rebrands to Section, launches new certificates", "行业媒体报道（Poets&Quants for Execs）", "2023-05",
       "2023-03 更名 Section；会员 $995/年；2022-03 时 15,000+ 校友；85–90% 讲师为 VP／C 级",
       "https://poetsandquantsforexecs.com/news/section4-rebrands-to-section-launches-new-certificates-for-business-professionals/",
       "支持 Section 由教授转向实践者讲师、会员定价。",
       "公司提供的数字。"),
    ev("e-section-ti", "Section launches AI curriculum", "公司新闻稿（Training Industry 发布）", "2023-09-19",
       "12 个月推出 50 门 AI 课；累计 33,000 学员、97 国；200+ 企业伙伴",
       "https://trainingindustry.com/press-release/strategy-alignment-and-planning/section-launches-industry-leading-ai-curriculum-to-build-the-new-ai-class-of-knowledge-workers/",
       "支持 Section 在 2023 年转向 AI 课程与企业客户。",
       "新闻稿自述。"),
    ev("e-section-about", "Section About", "公司官网", ACCESS,
       "当前产品：Section HQ（面向 AI 负责人的采用度量）、Section Coach（AI 教练）；面向企业 AI 落地",
       "https://www.sectionai.com/about",
       "支持 Section 已从课程转为企业 AI 采用软件＋服务。",
       "无客户数与收入。"),
]
